"use client";

import { useEffect, useRef, useState } from "react";
import { awe, type Edition, type Portal, memoriesByEdition, memoryForEdition, rooms } from "./museum-data";

function SparrowSound() {
  const [on, setOn] = useState(false);
  const play = () => { setOn(true); const AudioCtx = window.AudioContext || (window as typeof window & { webkitAudioContext: typeof AudioContext }).webkitAudioContext; if (!AudioCtx) return; const ctx = new AudioCtx(); [0, .12, .21].forEach((t, i) => { const osc = ctx.createOscillator(); const gain = ctx.createGain(); osc.type = "sine"; osc.frequency.value = [2400, 3100, 2700][i]; gain.gain.setValueAtTime(0, ctx.currentTime + t); gain.gain.linearRampToValueAtTime(.035, ctx.currentTime + t + .015); gain.gain.exponentialRampToValueAtTime(.001, ctx.currentTime + t + .09); osc.connect(gain).connect(ctx.destination); osc.start(ctx.currentTime + t); osc.stop(ctx.currentTime + t + .1); }); setTimeout(() => setOn(false), 650); };
  return <button className={`sound ${on ? "playing" : ""}`} onClick={play} aria-label="Play a small musical impression of birdsong"><span>♪</span> a small impression of birdsong</button>;
}

export default function Home() {
  const [edition, setEdition] = useState<Edition>("public"); const [entered, setEntered] = useState(false); const [portal, setPortal] = useState<Portal | null>(null); const [door, setDoor] = useState<number | null>(null); const dialogRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (!portal) return; const scrollY = window.scrollY; const previousFocus = document.activeElement as HTMLElement | null; document.body.classList.add("modal-open"); document.body.style.top = `-${scrollY}px`; dialogRef.current?.focus(); const handleKey = (event: KeyboardEvent) => { if (event.key === "Escape") { setPortal(null); return; } if (event.key !== "Tab" || !dialogRef.current) return; const focusable = dialogRef.current.querySelectorAll<HTMLElement>('button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])'); const first = focusable[0]; const last = focusable[focusable.length - 1]; if (!first || !last) return; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } }; document.addEventListener("keydown", handleKey); return () => { document.removeEventListener("keydown", handleKey); document.body.classList.remove("modal-open"); document.body.style.top = ""; window.scrollTo(0, scrollY); previousFocus?.focus(); }; }, [portal]);
  const displayedMemories = memoriesByEdition[edition];
  return <main data-edition={edition}>
    <section className={`opening ${entered ? "departed" : ""}`} aria-label="Museum entrance"><p className="eyebrow">A PERSONAL MUSEUM</p><h1>AN AUTOBIOGRAPHY<br/>TOLD THROUGH LOVE</h1><p className="subtitle">A collection of things that delighted me, changed me, broke me, and brought me home.</p><div className="edition-switch" role="group" aria-label="Choose an edition"><button className={edition === "public" ? "active" : ""} onClick={() => setEdition("public")} aria-pressed={edition === "public"}>Public edition</button><button className={edition === "private" ? "active" : ""} onClick={() => setEdition("private")} aria-pressed={edition === "private"}>Private edition</button></div><p className="edition-note">{edition === "public" ? "The story, with a little held close." : "The complete archive. More names, more detail, less distance."}</p><button className="enter" onClick={() => { setEntered(true); setTimeout(() => document.querySelector("#collection")?.scrollIntoView({behavior:"smooth"}), 450); }}>Enter the collection <span>↓</span></button><div className="moon" aria-hidden="true" /><p className="entrance-note">An autobiography measured in<br/>affections, not years.</p></section>
    <nav className="museum-nav" aria-label="Museum rooms"><span className="nav-edition">{edition} edition</span><a href="#collection">The collection</a><a href="#moments">Altered chemistry</a><a href="#thresholds">Thresholds</a><a href="#home">Coming home</a><button onClick={() => setEdition(edition === "public" ? "private" : "public")}>View {edition === "public" ? "private" : "public"}</button></nav>
    <section id="collection" className="collection"><header className="section-intro reveal"><p className="eyebrow">ROOMS 01–08</p><h2>The Things<br/><em>I Love</em></h2><p>Begin anywhere. The objects know the way.</p></header><div className="rooms">{rooms.map((room) => <article className={`room room-${room.number}`} key={room.title}><header><span>{room.number}</span><h3>{room.title}</h3><small>{String(room.items.length).padStart(2,"0")} OBJECTS</small></header><div className="object-grid">{room.items.map((item) => { const memory = memoryForEdition(item, edition); return <button key={item.name} className={`object ${item.name.includes("Aspen") ? "aspen" : ""} ${item.name === "Stracciatella" ? "quiet" : ""}`} onClick={() => memory && setPortal(item)} disabled={!memory}><span className="kind">{item.kind || ""}</span><strong>{item.name}</strong>{memory && <span className="inspect">open memory ↗</span>}{item.name.includes("Aspen") && <i className="leaves" aria-hidden="true">● ● ● ● ● ●</i>}</button>; })}</div>{room.title === "Nature" && <SparrowSound />}</article>)}</div><p className="ordinary">Not everything we love needs to be profound<br/>to belong in the story of our lives.</p></section>
    <section id="moments" className="moments"><header className="moments-title"><p className="eyebrow">ROOMS 09–12 · PLEASE MOVE GENTLY</p><h2>Moments That Altered<br/>My Brain Chemistry</h2></header><article className="deep-room awe"><div className="sticky"><p>09</p><h3>Awe</h3><span>The world, briefly<br/>larger than language.</span></div><ol>{awe.map((x,i)=><li key={x}><span>{String(i+1).padStart(2,"0")}</span><p>{x}</p>{x.includes("Matterhorn") && <div className="matterhorn" aria-hidden="true"><i/><b>clouds clear on hover</b></div>}</li>)}</ol></article><article className="deep-room adult"><div className="sticky"><p>10</p><h3>Becoming<br/>an Adult</h3><span>No ceremony.<br/>Just a before and after.</span></div><ol>{displayedMemories.adult.map((x,i)=><li key={x}><span>{String(i+1).padStart(2,"0")}</span><p>{x}</p></li>)}</ol></article><article className="loss"><header><p>ROOM 11</p><h3>Loss</h3>{edition === "public" && <span className="curatorial-note">Some things are allowed to remain unnamed.</span>}</header><div className="loss-list">{displayedMemories.loss.map((x,i)=><p key={x}><span>{String(i+1).padStart(2,"0")}</span>{x}</p>)}</div></article></section>
    <section id="thresholds" className="thresholds"><header><p className="eyebrow">ROOM 12 · A HALLWAY</p><h2>Thresholds</h2><p>Every door is both an entrance and an exit.</p></header><div className="hallway">{displayedMemories.thresholds.map(([label,text],i)=><button className={`door ${door===i ? "open" : ""}`} key={label} onClick={()=>setDoor(door===i?null:i)} aria-expanded={door===i}><span className="door-number">{String(i+1).padStart(2,"0")}</span><span className="door-face"><i/><b>{label}</b><em>enter</em></span><span className="door-memory">{text}</span></button>)}</div><p className="blank-space">And then, for a while, nothing lined up.</p></section>
    <section id="home" className="coming-home"><div className="home-mark">⌂</div><p className="eyebrow">THE FINAL ROOM</p><h2>Coming Home</h2><div className="essay"><p>There was a time when I didn’t know who I was anymore.</p><p>I felt like I had lost my spark. I remember telling a friend, “I don’t know who I am anymore,” and they replied, “What do you mean? You’re Salene.”</p><p>But, who was she? I wanted to know who I was outside of all the external identities I had built around myself. For a long time, I didn’t have an answer.</p><p>Maybe this collection is part of my pilgrimage back to myself. It began as a list of favorite things, but somewhere along the way it became a map. Every entry became a reminder: this still delights me. This still moves me. This still feels like home.</p><p>I don’t know if anyone can ever say they’ve completely arrived. Maybe coming home to yourself isn’t a destination so much as a practice of remembering. But if I ever lose my way again, I hope this collection reminds me of who I am.</p></div><footer><span>Last updated: whenever I discover something else I love.</span><a href="#collection">Begin again ↑</a></footer></section>
    {portal && <div className="portal-backdrop"><button className="portal-dismiss" onClick={()=>setPortal(null)} aria-hidden="true" tabIndex={-1} /><div className={`portal ${portal.name === "Stracciatella" ? "stracciatella" : ""}`} role="dialog" aria-modal="true" aria-labelledby="memory-title" tabIndex={-1} ref={dialogRef}><button className="close" onClick={()=>setPortal(null)} aria-label="Close memory">×</button><p>{portal.kind || "OBJECT"}</p><h3 id="memory-title">{portal.name}</h3><blockquote>{memoryForEdition(portal, edition)}</blockquote></div></div>}
  </main>;
}
