const route = ["香港 Hong Kong","台山 Taishan","广州 Guangzhou","开平 Kaiping","昆明 Kunming","大理 Dali","丽江 Lijiang","香格里拉 Shangri-La","佛山 Foshan","珠海 Zhuhai"];
const routePinyin = ["Xiānggǎng","Táishān","Guǎngzhōu","Kāipíng","Kūnmíng","Dàlǐ","Lìjiāng","Xiānggélǐlā","Fóshān","Zhūhǎi"];
const choicePinyin = {
  "不好意思，我听不懂。可以发短信吗？":"Bù hǎoyìsi, wǒ tīng bù dǒng. Kěyǐ fā duǎnxìn ma?","我在这里！":"Wǒ zài zhèlǐ!","我听一点普通话，可以慢一点吗？":"Wǒ tīng yìdiǎn Pǔtōnghuà, kěyǐ màn yìdiǎn ma?","我是美国人。":"Wǒ shì Měiguó rén.",
  "可以帮我吗？我的护照在这里。":"Kěyǐ bāng wǒ ma? Wǒ de hùzhào zài zhèlǐ.","这个？那个？":"Zhège? Nàge?","我要去开平。":"Wǒ yào qù Kāipíng.","不要辣。我要这个，谢谢。":"Bú yào là. Wǒ yào zhège, xièxie.","一点点辣。":"Yìdiǎndiǎn là.","不要！":"Bú yào!",
  "我有预订。这是我的护照。":"Wǒ yǒu yùdìng. Zhè shì wǒ de hùzhào.","有，有，有。":"Yǒu, yǒu, yǒu.","祖庙在哪里？怎么走？":"Zǔmiào zài nǎlǐ? Zěnme zǒu?","左边？右边？":"Zuǒbian? Yòubian?","这里很漂亮。":"Zhèlǐ hěn piàoliang.",
  "太贵了。可以便宜一点吗？":"Tài guì le. Kěyǐ piányi yìdiǎn ma?","多少钱？":"Duōshao qián?","不要，谢谢。":"Bú yào, xièxie.","不好意思，我想租自行车。":"Bù hǎoyìsi, wǒ xiǎng zū zìxíngchē.","不是奶奶！自行车！":"Bú shì nǎinai! Zìxíngchē!","可以帮我吗？":"Kěyǐ bāng wǒ ma?",
  "我听一点。请慢一点，再说一次。":"Wǒ tīng yìdiǎn. Qǐng màn yìdiǎn, zài shuō yí cì.","可以发短信吗？":"Kěyǐ fā duǎnxìn ma?","明天…八点？":"Míngtiān… bā diǎn?"
};

const scenarios = [
  {location:0,kicker:"THE AIRPORT / 14% BATTERY",title:"Your Didi driver is calling. Calling.",cn:"喂？",danger:"PERSONAL",npc:"师傅已经到了，你在哪里？<small>Shīfu yǐjīng dào le, nǐ zài nǎlǐ?</small>",prompt:"He has arrived. You have not. What do you say?",lesson:["听不懂，可以发短信吗？","Tīng bù dǒng, kěyǐ fā duǎnxìn ma?","I don’t understand. Can you text me?"],context:"听不懂 is blunt but useful. Add 不好意思 (sorry/excuse me) when you want to soften it.",choices:[
    ["A","不好意思，我听不懂。可以发短信吗？","Bù hǎoyìsi… can you text me?",2,"EXCELLENT PANIC MANAGEMENT","He texts you. The international crisis has been downgraded to a blue dot on a map."],
    ["B","我在这里！","I’m here!",1,"TECHNICALLY A SENTENCE","True, but ‘here’ is doing dangerous amounts of work. Follow with a landmark or send your location."],
    ["C","Hello? HELLO? Airport. Me. Blue shirt.","International charades",0,"THE DRIVER ALSO HAS QUESTIONS","You have communicated several nouns and a vibe. Somehow, he finds you."],
    ["D","Hang up. Enter witness protection.","A classic",-1,"STRATEGIC RETREAT","The driver cancels. You learn nothing, but your screen time report gets exciting."]]},
  {location:1,kicker:"VILLAGE MODE / DIALECT DETECTED",title:"Mandarin has left the chat.",cn:"台山",danger:"LINGUISTIC",npc:"NPC says something warm and rapid in Toisanese.<small>[Your textbook begins smoking.]</small>",prompt:"You catch exactly zero words. Deploy honesty.",lesson:["我听一点普通话。","Wǒ tīng yìdiǎn Pǔtōnghuà.","I understand a little Mandarin."],context:"普通话 means Standard Mandarin. In Taishan, many people also speak Toisanese (台山话), a distinct Yue variety.",choices:[
    ["A","我听一点普通话，可以慢一点吗？","I understand a little Mandarin. Slower?",2,"CROSS-DIALECT DIPLOMACY","They switch to slower Mandarin and adopt you immediately."],
    ["B","我是美国人。","I am American.",1,"CONTEXT: PROVIDED","Not an answer, but it explains a lot. Pair it with 我听不懂 for maximum utility."],
    ["C","Smile and accept three bowls of soup.","The ancestral method",0,"YOU HAVE BEEN FED","Language failed. Hospitality did not. This still counts as survival."],
    ["D","Respond in your Duolingo accent.","Surely this helps",-1,"THE OWL CANNOT SAVE YOU","No one understands. Somewhere, a streak freezes."]]},
  {location:2,kicker:"GUANGZHOU SOUTH / GATE CLOSING",title:"The train waits for no learner.",cn:"高铁",danger:"8 MINUTES",npc:"请出示您的身份证件。<small>Qǐng chūshì nín de shēnfèn zhèngjiàn.</small>",prompt:"The attendant wants identification. Your passport is somewhere inside your emotional-support tote bag.",lesson:["可以帮我吗？","Kěyǐ bāng wǒ ma?","Can you help me?"],context:"请 (please) and 可以…吗？ (may/can…?) make requests polite. Pointing is a valid supporting technology.",choices:[
    ["A","可以帮我吗？我的护照在这里。","Can you help me? My passport is here.",2,"PLATFORM ACQUIRED","A staff member points, you sprint, and high-speed rail becomes high-speed cardio."],
    ["B","这个？那个？","This one? That one?",1,"MINIMALIST BUT EFFECTIVE","Two tiny words plus determined pointing can move mountains. Or at least a queue."],
    ["C","我要去开平。","I want to go to Kaiping.",0,"DESTINATION: NOT THE QUESTION","Useful information, wrong moment. She is still waiting for your passport."],
    ["D","Begin unpacking every object you own.","Public performance art",-1,"GATE CLOSING","You present a charger, lip balm, and one mysterious receipt. None are valid ID."]]},
  {location:3,kicker:"LUNCH / NO ENGLISH MENU",title:"Restaurant roulette begins.",cn:"点菜",danger:"DELICIOUS",npc:"要辣吗？<small>Yào là ma?</small>",prompt:"Important question: Do you want it spicy? Your stomach has retained legal counsel.",lesson:["不要辣。我要这个。","Bú yào là. Wǒ yào zhège.","Not spicy. I want this one."],context:"要 means want; 不要 means don’t want. Before a fourth tone, 不 changes pronunciation from bù to bú.",choices:[
    ["A","不要辣。我要这个，谢谢。","Not spicy. I want this. Thanks.",2,"LUNCH SECURED","Clear, polite, and only mildly dependent on pointing. Michelin-star survival."],
    ["B","一点点辣。","A tiny bit spicy.",2,"BRAVE AND SPECIFIC","一点点 is ‘just a little.’ Local definitions of ‘little’ may differ."],
    ["C","不要！","DON’T WANT!",0,"THE ENTIRE RESTAURANT PAUSES","Grammatically valid. Socially, add what you don’t want—or at least a smile."],
    ["D","Pretend you love spicy food.","A future-you problem",-1,"HUBRIS, SERVED HOT","The dish arrives glowing. You see through time." ] ]},
  {location:4,kicker:"HOTEL CHECK-IN / 11:47 PM",title:"They need a deposit. You need a bed.",cn:"入住",danger:"SLEEPY",npc:"请问您有预订吗？<small>Qǐngwèn nín yǒu yùdìng ma?</small>",prompt:"Do you have a reservation? You absolutely do. Somewhere in the booking system’s creative interpretation of your name.",lesson:["我有预订。这是我的护照。","Wǒ yǒu yùdìng. Zhè shì wǒ de hùzhào.","I have a reservation. This is my passport."],context:"有 means ‘to have’ or ‘there is.’ 没有 means ‘do not have’ or ‘there isn’t.’ Extremely useful pair.",choices:[
    ["A","我有预订。这是我的护照。","I have a reservation. This is my passport.",2,"ROOM KEY UNLOCKED","The reservation exists. Your passport survives another photocopier."],
    ["B","有，有，有。","Have, have, have.",1,"ENTHUSIASTICALLY CORRECT","You sound like a delighted pigeon, but the key card appears."],
    ["C","我是美国人。","I am American.",0,"AGAIN: NOT THE QUESTION","This phrase is becoming your conversational smoke bomb."],
    ["D","Sleep in the lobby plant.","Photosynthesis mode",-1,"BOTANICAL CHECK-IN","Housekeeping is impressed but concerned." ] ]},
  {location:5,kicker:"FOSHAN OLD TOWN / CONFIDENCE PEAKING",title:"You are lost with authority.",cn:"迷路",danger:"SIDE QUEST",npc:"你要去哪里？<small>Nǐ yào qù nǎlǐ?</small>",prompt:"Where are you trying to go? Great question. Ask for the ancestral temple.",lesson:["祖庙在哪里？怎么走？","Zǔmiào zài nǎlǐ? Zěnme zǒu?","Where is the Ancestral Temple? How do I get there?"],context:"在哪里 asks where something is. 怎么走 asks how to walk/get there. Listen for 左边 (left), 右边 (right), 前面 (ahead).",
  choices:[["A","祖庙在哪里？怎么走？","Where is the temple? How do I get there?",2,"HUMAN GPS ACTIVATED","They point ahead and right: 前面，右边. You understand two whole directions."],["B","左边？右边？","Left? Right?",1,"BINARY NAVIGATION","You have reduced a city to two options. Honestly, elegant."],["C","这里很漂亮。","It’s beautiful here.",0,"TRUE BUT LOST","A lovely compliment. The temple remains theoretical."],["D","Follow the most confident grandma.","She knows things",0,"UNAUTHORIZED TOUR GROUP","She leads you to a pharmacy. You buy tissues out of respect."]]},
  {location:6,kicker:"KUNMING MARKET / WALLET EXPOSED",title:"The jade bracelet chooses you.",cn:"砍价",danger:"FINANCIAL",npc:"三百八，很便宜！<small>Sānbǎi bā, hěn piányi!</small>",prompt:"¥380, ‘very cheap.’ The vendor has identified you as spiritually purchasable.",lesson:["太贵了。可以便宜一点吗？","Tài guì le. Kěyǐ piányi yìdiǎn ma?","Too expensive. Can it be a little cheaper?"],context:"太…了 means ‘too…’. Bargaining can be expected in markets, but not in malls or fixed-price shops. Keep it playful.",choices:[
    ["A","太贵了。可以便宜一点吗？","Too expensive. A little cheaper?",2,"NEGOTIATION UNLOCKED","The price drops. You are now an economist with a bracelet."],
    ["B","多少钱？","How much?",1,"YOU RESTARTED THE CONVERSATION","Useful phrase, but she did just tell you. Confidence is sometimes repetition."],
    ["C","不要，谢谢。","I don’t want it, thanks.",2,"BOUNDARY ACHIEVED","The cheapest purchase is no purchase. Your suitcase applauds."],
    ["D","Pay immediately and call it cultural exchange.","Generosity mode",-1,"PREMIUM TOURIST PRICING","The vendor’s ancestors feel a sudden warmth." ] ]},
  {location:7,kicker:"DALI / TRANSLATOR BETRAYAL",title:"Your app has become an agent of chaos.",cn:"翻译",danger:"AI",npc:"APP OUTPUT: 我想租你的奶奶。<small>Wǒ xiǎng zū nǐ de nǎinai. / I want to rent your grandma.</small>",prompt:"You meant: ‘I want to rent a bicycle.’ Repair relations immediately.",lesson:["不好意思，我想租自行车。","Bù hǎoyìsi, wǒ xiǎng zū zìxíngchē.","Sorry, I’d like to rent a bicycle."],context:"奶奶 is grandma. 自行车 is bicycle. Translation tools are drafts, not diplomatic immunity.",choices:[
    ["A","不好意思，我想租自行车。","Sorry, I want to rent a bicycle.",2,"GRANDMA RELEASED","The shopkeeper laughs. Grandma remains autonomous. You get a bike."],
    ["B","不是奶奶！自行车！","Not grandma! Bicycle!",1,"URGENT CLARIFICATION","Abrupt but vitally important for all parties."],
    ["C","可以帮我吗？","Can you help me?",1,"HELP: SUMMONED","A bystander repairs both the sentence and the international incident."],
    ["D","Double down and ask the hourly rate.","No.",-2,"ABSOLUTELY NOT","The app is confiscated for everyone’s safety." ] ]},
  {location:9,kicker:"SHANGRI-LA / FINAL BOSS",title:"The phone rings. There is no text option.",cn:"终极",danger:"MAXIMUM",npc:"喂？您好，我是酒店前台。您明天早上几点出发？<small>Hello, hotel front desk. What time do you leave tomorrow morning?</small>",prompt:"You understood ‘hotel,’ ‘tomorrow morning,’ and the sound of your own heartbeat.",lesson:["我听一点。请慢一点，再说一次。","Wǒ tīng yìdiǎn. Qǐng màn yìdiǎn, zài shuō yí cì.","I understand a little. Please speak slowly and say it again."],context:"请慢一点 (please slow down) and 再说一次 (say it again) keep a conversation alive. You don’t need perfection—just repair strategies.",choices:[
    ["A","我听一点。请慢一点，再说一次。","I understand a little. Slower, one more time.",3,"FINAL BOSS DEFEATED","They repeat slowly. You arrange a 早上八点 departure. That was a whole phone call."],
    ["B","可以发短信吗？","Can you text me?",2,"THE SACRED TECHNIQUE","Effective, honest, and the reason society invented messaging."],
    ["C","明天…八点？","Tomorrow… eight?",1,"CAVEMAN FLUENCY","Three words, one rising intonation, successful logistics. Language is miraculous."],
    ["D","Hang up and stare at the phone.","The original strategy",-1,"A PERFECT CIRCLE","You end exactly where you began—but now you know what you should have said." ] ]}
];

const scenarioRoute = [0,1,2,3,9,8,4,5,7];
scenarios.forEach((scenario,index)=>scenario.location=scenarioRoute[index]);

let state={scene:0,score:0,nerve:3,streak:0,bestStreak:0,phrases:[]};
const $=id=>document.getElementById(id);
const screens=["heroScreen","briefingScreen","gameScreen","resultsScreen"];
const prefersReducedMotion=window.matchMedia("(prefers-reduced-motion: reduce)");
const scrollBehavior=()=>prefersReducedMotion.matches?"auto":"smooth";
function show(id){screens.forEach(s=>$(s).classList.toggle("active",s===id));window.scrollTo({top:0,behavior:scrollBehavior()})}
function beep(ok=true){if(!soundOn)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);o.frequency.value=ok?520:170;g.gain.setValueAtTime(.05,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.13);o.onended=()=>c.close();o.start();o.stop(c.currentTime+.13)}
let soundOn=true;
function speak(text){if(!soundOn||!("speechSynthesis" in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="zh-CN";u.rate=.72;speechSynthesis.speak(u)}
function reset(){state={scene:0,score:0,nerve:3,streak:0,bestStreak:0,phrases:[]};updateStatus();renderRoute()}
function updateStatus(){$("nerveLabel").textContent=state.nerve;$("streakLabel").textContent=state.streak;$("phraseCount").textContent=`${state.phrases.length} / ${scenarios.length}`}
function renderRoute(){const current=scenarios[Math.min(state.scene,scenarios.length-1)]?.location??0;$("routeList").innerHTML=route.map((r,i)=>`<li class="${i<current?'done':i===current?'current':''}">${r}<span class="route-pinyin">${routePinyin[i]}</span></li>`).join("")}
function renderScene(){const s=scenarios[state.scene],npcChinese=s.npc.split("<small>")[0],iconPos=[["0%","0%"],["50%","0%"],["100%","0%"],["0%","50%"],["50%","50%"],["100%","50%"],["0%","100%"],["50%","100%"],["100%","100%"]][state.scene];$("locationLabel").textContent=route[s.location].split(" ").slice(1).join(" ").toUpperCase();$("sceneNumber").textContent=`CRISIS ${String(state.scene+1).padStart(2,"0")} / ${String(scenarios.length).padStart(2,"0")}`;$("dangerLabel").textContent=`DANGER: ${s.danger}`;$("sceneKicker").textContent=s.kicker;$("sceneTitle").textContent=s.title;$("npcBubble").innerHTML=s.npc;$("npcSpeak").onclick=()=>speak(npcChinese);$("scenePrompt").textContent=s.prompt;$("sceneVisual").dataset.cn=s.cn;$("sceneVisual").style.setProperty("--icon-x",iconPos[0]);$("sceneVisual").style.setProperty("--icon-y",iconPos[1]);$("sceneVisual").style.background=["#84cbe9","#a6d998","#ff8eaa","#ffe36b","#e8d5fc","#c8f0e2","#f8d3a1","#c7e8fb","#e8d5fc"][state.scene];$("choices").innerHTML=s.choices.map((c,i)=>{const py=choicePinyin[c[1]];return `<div class="choice-row ${py?"has-audio":""}"><button type="button" class="choice" data-index="${i}"><b>${c[0]}</b><span class="choice-text">${c[1]}${py?`<small class="choice-pinyin">${py}</small>`:""}<small>${c[2]}</small></span></button>${py?`<button type="button" class="choice-audio" data-phrase="${c[1]}" aria-label="Hear this answer"></button>`:""}</div>`}).join("");$("feedbackCard").classList.remove("show");$("sceneCard").style.display="block";renderRoute();updateStatus();document.querySelectorAll(".choice").forEach(b=>b.addEventListener("click",()=>choose(+b.dataset.index)));document.querySelectorAll(".choice-audio").forEach(b=>b.addEventListener("click",()=>speak(b.dataset.phrase)))}
function choose(i){const s=scenarios[state.scene],c=s.choices[i],points=typeof c[3]==="number"?c[3]:0;if($("feedbackCard").classList.contains("show"))return;state.score+=Math.max(0,points);if(points<0)state.nerve=Math.max(0,state.nerve-1);if(points>=2){state.streak++;state.bestStreak=Math.max(state.bestStreak,state.streak)}else state.streak=0;if(!state.phrases.includes(s.lesson[0]))state.phrases.push(s.lesson[0]);$("verdictIcon").textContent=points>=2?"STRONG":points>=0?"STILL ALIVE":"NERVE LOST";$("verdict").textContent=c[4];$("scoreChange").textContent=points>0?`+${points} SURVIVAL`:points<0?`${points} NERVE`:"CHARACTER +1";$("feedbackText").textContent=c[5];$("lessonChinese").textContent=s.lesson[0];$("lessonPinyin").textContent=s.lesson[1];$("lessonMeaning").textContent=s.lesson[2];$("contextText").textContent=`FIELD NOTE: ${s.context}`;$("lessonSpeak").onclick=()=>speak(s.lesson[0]);$("nextButton").textContent=state.scene===scenarios.length-1?"SEE TRIP REPORT →":"NEXT CRISIS →";$("feedbackCard").classList.add("show");document.querySelectorAll(".choice").forEach(b=>b.disabled=true);updateStatus();beep(points>=0);setTimeout(()=>$("feedbackCard").scrollIntoView({behavior:scrollBehavior(),block:"center"}),120)}
function results(){show("resultsScreen");$("finalScore").textContent=state.score;$("finalPhrases").textContent=state.phrases.length;$("finalStreak").textContent=state.bestStreak;const rank=state.score>=16?"传奇":state.score>=11?"能活":state.score>=6?"勇敢":"迷路";$("finalRank").textContent=rank;$("resultHeadline").textContent=state.nerve===0?"BARELY ALIVE.":state.score>=16?"YOU ABSOLUTELY SURVIVED.":"YOU SURVIVED. SOMEHOW.";$("resultCopy").textContent=state.score>=16?"You negotiated, navigated, ordered lunch, and answered an actual phone call. Mandarin did not become easy. You became resourceful.":"You missed some cues, invented several strategies, and kept going. That is, inconveniently, how real language learning works.";$("phraseRecap").innerHTML=state.phrases.map(p=>`<span>${p}</span>`).join("")}
$("startButton").onclick=()=>show("briefingScreen");$("beginTrip").onclick=()=>{reset();show("gameScreen");renderScene()};$("nextButton").onclick=()=>{if(++state.scene>=scenarios.length)results();else{renderScene();window.scrollTo({top:0,behavior:scrollBehavior()})}};$("replayButton").onclick=()=>{reset();show("gameScreen");renderScene()};document.querySelectorAll('[data-action="home"]').forEach(b=>b.onclick=()=>show("heroScreen"));document.querySelectorAll("[data-speak]").forEach(b=>b.onclick=()=>speak(b.dataset.speak));$("soundToggle").onclick=()=>{soundOn=!soundOn;$("soundToggle").textContent=`SOUND: ${soundOn?"ON":"OFF"}`;$("soundToggle").setAttribute("aria-pressed",String(soundOn))};renderRoute();
